version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/schoolbustracker
    file_exists_behavior: OVERWRITE
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
      runas: root